spring:
  jackson:
    time-zone: GMT+8
  thymeleaf:
    prefix: classpath:/static/
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///cinema?useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 1234


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl